version: "3"

services:
  nodejs:
    image: nodejs
    build:
      context: .
      dockerfile: Dockerfile
    container_name: health-journal-backend
    restart: always
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    command: npm run start

volumes:
  node_modules:
